# Generated by Django 3.1.5 on 2021-01-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='number_campers',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
