# Generated by Django 3.1.5 on 2021-01-14 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210113_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AlterField(
            model_name='coach',
            name='pic',
            field=models.ImageField(blank=True, upload_to='coaches'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='gymnast',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
